AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  SuggestExtensions: false
  Exclude:
    - 'spec/**/*'
    - 'vendor/**/*'

Gemspec/RequiredRubyVersion:
  Enabled: false
Layout/LineLength:
  Max: 100
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false
Metrics/MethodLength:
  Max: 12
Style/Documentation:
  Enabled: false
Style/RedundantFetchBlock:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/RaiseArgs:
  EnforcedStyle: exploded
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
